#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop the service before removal
        if systemctl is-active --quiet tune-server.service; then
            systemctl stop tune-server.service
        fi
        ;;
esac

# Automatically added by dh_installsystemd/13.14.1ubuntu5
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'tune-server.service' >/dev/null || true
fi
# End automatically added section


exit 0
