"""initial schema — 24 tables

Revision ID: d93e0ecaaaf9
Revises: 
Create Date: 2026-04-14 10:12:44.040940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93e0ecaaaf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_credentials',
    sa.Column('device_id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.Text(), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('metadata_fix_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('tracks_scanned', sa.Integer(), server_default='0', nullable=True),
    sa.Column('auto_fixed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('suggestions', sa.Integer(), server_default='0', nullable=True),
    sa.Column('errors', sa.Integer(), server_default='0', nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_service', sa.Text(), nullable=False),
    sa.Column('source_playlist_id', sa.Text(), nullable=False),
    sa.Column('playlist_name', sa.Text(), nullable=True),
    sa.Column('track_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('snapshot_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artist', sa.Text(), server_default='', nullable=False),
    sa.Column('station_name', sa.Text(), server_default='', nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('stream_url', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_radio_favorites_dedup', 'radio_favorites', ['title', 'artist'], unique=True)
    op.create_table('transfer_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('source_service', sa.Text(), nullable=True),
    sa.Column('source_playlist_id', sa.Text(), nullable=True),
    sa.Column('source_playlist_name', sa.Text(), nullable=True),
    sa.Column('target_service', sa.Text(), nullable=True),
    sa.Column('target_playlist_id', sa.Text(), nullable=True),
    sa.Column('target_playlist_name', sa.Text(), nullable=True),
    sa.Column('total_tracks', sa.Integer(), server_default='0', nullable=True),
    sa.Column('matched', sa.Integer(), server_default='0', nullable=True),
    sa.Column('approximate', sa.Integer(), server_default='0', nullable=True),
    sa.Column('not_found', sa.Integer(), server_default='0', nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('avatar_color', sa.Text(), server_default='#FF6B35', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_playlist_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('service_playlist_id', sa.Text(), nullable=False),
    sa.Column('service_playlist_name', sa.Text(), nullable=True),
    sa.Column('sync_direction', sa.Text(), server_default='pull', nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['local_playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('leader_zone_id', sa.Integer(), nullable=True),
    sa.Column('master_volume', sa.Float(), server_default='0.5', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['leader_zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_link_id', sa.Integer(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), server_default='60', nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['playlist_link_id'], ['playlist_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('volume_offset', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('muted', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['zone_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'zone_id')
    )
    op.create_table('duplicate_tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id_a', sa.Integer(), nullable=True),
    sa.Column('track_id_b', sa.Integer(), nullable=True),
    sa.Column('audio_hash', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.ForeignKeyConstraint(['track_id_a'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id_b'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('suggested_value', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_favorites_user', 'user_favorites', ['user_id'], unique=False)
    op.drop_table('artists_fts_docsize')
    op.drop_table('tracks_fts_idx')
    op.drop_table('tracks_fts')
    op.drop_table('tracks_fts_docsize')
    op.drop_table('albums_fts_data')
    op.drop_table('artists_fts_data')
    op.drop_table('tracks_fts_data')
    op.drop_table('artists_fts_idx')
    op.drop_table('albums_fts_config')
    op.drop_table('artists_fts_config')
    op.drop_table('artists_fts')
    op.drop_table('albums_fts_docsize')
    op.drop_table('albums_fts_idx')
    op.drop_table('tracks_fts_config')
    op.drop_table('albums_fts')
    op.add_column('albums', sa.Column('musicbrainz_release_id', sa.Text(), nullable=True))
    op.add_column('albums', sa.Column('label', sa.Text(), nullable=True))
    op.add_column('albums', sa.Column('catalog_number', sa.Text(), nullable=True))
    op.add_column('albums', sa.Column('barcode', sa.Text(), nullable=True))
    op.add_column('albums', sa.Column('format', sa.Text(), nullable=True))
    op.add_column('albums', sa.Column('sample_rate', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('bit_depth', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('artist_name', sa.Text(), nullable=True))
    op.alter_column('albums', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('albums', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('albums', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.create_foreign_key(None, 'albums', 'artists', ['artist_id'], ['id'], ondelete='SET NULL')
    op.add_column('artists', sa.Column('source_id', sa.Text(), nullable=True))
    op.alter_column('artists', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('artists', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('artists', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('network_mounts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('network_mounts', 'mount_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('network_mounts', 'auto_mount',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('network_mounts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('network_mounts', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('play_queue', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'play_queue', type_='foreignkey')
    op.drop_constraint(None, 'play_queue', type_='foreignkey')
    op.create_foreign_key(None, 'play_queue', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'play_queue', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.alter_column('playlist_tracks', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'playlist_tracks', type_='foreignkey')
    op.drop_constraint(None, 'playlist_tracks', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_tracks', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'playlist_tracks', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.alter_column('playlists', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('playlists', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('playlists', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('radio_stations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('radio_stations', 'favorite',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('radio_stations', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('radio_stations', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('streaming_auth', 'service',
               existing_type=sa.TEXT(),
               nullable=False,
               autoincrement=False)
    op.alter_column('streaming_auth', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('tracks', sa.Column('isrc', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('genre', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('composer', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('lyrics', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('musicbrainz_recording_id', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('acoustid', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('bpm', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('label', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('custom_tags', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('album_title', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('artist_name', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('cover_path', sa.Text(), nullable=True))
    op.alter_column('tracks', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('tracks', 'file_mtime',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('tracks', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('tracks', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.create_foreign_key(None, 'tracks', 'artists', ['artist_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tracks', 'albums', ['album_id'], ['id'], ondelete='SET NULL')
    op.add_column('zones', sa.Column('muted', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=True))
    op.add_column('zones', sa.Column('online', sa.Boolean(), server_default=sa.text('(TRUE)'), nullable=True))
    op.alter_column('zones', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('zones', 'volume',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('zones', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zones', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('zones', 'volume',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('zones', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('zones', 'online')
    op.drop_column('zones', 'muted')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.create_foreign_key(None, 'tracks', 'albums', ['album_id'], ['id'])
    op.create_foreign_key(None, 'tracks', 'artists', ['artist_id'], ['id'])
    op.alter_column('tracks', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('tracks', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('tracks', 'file_mtime',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('tracks', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('tracks', 'cover_path')
    op.drop_column('tracks', 'artist_name')
    op.drop_column('tracks', 'album_title')
    op.drop_column('tracks', 'custom_tags')
    op.drop_column('tracks', 'label')
    op.drop_column('tracks', 'bpm')
    op.drop_column('tracks', 'acoustid')
    op.drop_column('tracks', 'musicbrainz_recording_id')
    op.drop_column('tracks', 'comment')
    op.drop_column('tracks', 'lyrics')
    op.drop_column('tracks', 'year')
    op.drop_column('tracks', 'composer')
    op.drop_column('tracks', 'genre')
    op.drop_column('tracks', 'isrc')
    op.alter_column('streaming_auth', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('streaming_auth', 'service',
               existing_type=sa.TEXT(),
               nullable=True,
               autoincrement=False)
    op.alter_column('radio_stations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('radio_stations', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('radio_stations', 'favorite',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('radio_stations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('playlists', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('playlists', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('playlists', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'playlist_tracks', type_='foreignkey')
    op.drop_constraint(None, 'playlist_tracks', type_='foreignkey')
    op.create_foreign_key(None, 'playlist_tracks', 'tracks', ['track_id'], ['id'])
    op.create_foreign_key(None, 'playlist_tracks', 'playlists', ['playlist_id'], ['id'])
    op.alter_column('playlist_tracks', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'play_queue', type_='foreignkey')
    op.drop_constraint(None, 'play_queue', type_='foreignkey')
    op.create_foreign_key(None, 'play_queue', 'zones', ['zone_id'], ['id'])
    op.create_foreign_key(None, 'play_queue', 'tracks', ['track_id'], ['id'])
    op.alter_column('play_queue', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('network_mounts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('network_mounts', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('network_mounts', 'auto_mount',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('network_mounts', 'mount_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('network_mounts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('artists', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('artists', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('artists', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('artists', 'source_id')
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.create_foreign_key(None, 'albums', 'artists', ['artist_id'], ['id'])
    op.alter_column('albums', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('albums', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('albums', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('albums', 'artist_name')
    op.drop_column('albums', 'bit_depth')
    op.drop_column('albums', 'sample_rate')
    op.drop_column('albums', 'format')
    op.drop_column('albums', 'barcode')
    op.drop_column('albums', 'catalog_number')
    op.drop_column('albums', 'label')
    op.drop_column('albums', 'musicbrainz_release_id')
    op.create_table('albums_fts',
    sa.Column('title', sa.NullType(), nullable=True)
    )
    op.create_table('tracks_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('albums_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('albums_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists_fts',
    sa.Column('name', sa.NullType(), nullable=True)
    )
    op.create_table('artists_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('albums_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('artists_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('tracks_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artists_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albums_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks_fts',
    sa.Column('title', sa.NullType(), nullable=True)
    )
    op.create_table('tracks_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('artists_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_user_favorites_user', table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_table('metadata_suggestions')
    op.drop_table('duplicate_tracks')
    op.drop_table('zone_group_members')
    op.drop_table('sync_schedules')
    op.drop_table('zone_groups')
    op.drop_table('playlist_links')
    op.drop_table('zone_profiles')
    op.drop_table('user_profiles')
    op.drop_table('transfer_history')
    op.drop_index('idx_radio_favorites_dedup', table_name='radio_favorites')
    op.drop_table('radio_favorites')
    op.drop_table('playlist_snapshots')
    op.drop_table('metadata_fix_reports')
    op.drop_table('device_credentials')
    # ### end Alembic commands ###
