#!/usr/bin/env bash
# =============================================================================
# Tune Server — Interactive Setup
# Creates a .env file with your configuration.
# =============================================================================

set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}"
echo "  ╔══════════════════════════════════════╗"
echo "  ║       🎵  Tune Server Setup  🎵      ║"
echo "  ╚══════════════════════════════════════╝"
echo -e "${NC}"

ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}A .env file already exists. Overwrite? (y/N)${NC}"
    read -r overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# --- Music directory ---
echo -e "${CYAN}1. Where is your music?${NC}"
echo -n "   Music directory [~/Music]: "
read -r music_dir
music_dir=${music_dir:-~/Music}

# --- Database ---
echo ""
echo -e "${CYAN}2. Database engine${NC}"
echo "   1) SQLite (default, zero config)"
echo "   2) PostgreSQL (recommended for large libraries)"
echo -n "   Choice [1]: "
read -r db_choice
db_choice=${db_choice:-1}

db_engine="sqlite"
db_url=""
if [ "$db_choice" = "2" ]; then
    db_engine="postgres"
    echo -n "   PostgreSQL URL [postgresql://tuneserver:password@localhost/tune]: "
    read -r db_url
    db_url=${db_url:-postgresql://tuneserver:password@localhost/tune}
fi

# --- Port ---
echo ""
echo -e "${CYAN}3. Server port${NC}"
echo -n "   HTTP port [8888]: "
read -r port
port=${port:-8888}

# --- Streaming services ---
echo ""
echo -e "${CYAN}4. Streaming services (enable the ones you use)${NC}"

echo -n "   Enable Tidal? (y/N): "
read -r tidal
tidal_enabled=$( [ "$tidal" = "y" ] || [ "$tidal" = "Y" ] && echo "true" || echo "false" )

echo -n "   Enable Qobuz? (y/N): "
read -r qobuz
qobuz_enabled=$( [ "$qobuz" = "y" ] || [ "$qobuz" = "Y" ] && echo "true" || echo "false" )

echo -n "   Enable Deezer? (y/N): "
read -r deezer
deezer_enabled="false"
deezer_arl=""
if [ "$deezer" = "y" ] || [ "$deezer" = "Y" ]; then
    deezer_enabled="true"
    echo "   → To get your Deezer ARL cookie:"
    echo "     1. Log in to deezer.com"
    echo "     2. Open DevTools (F12) → Application → Cookies"
    echo "     3. Copy the 'arl' cookie value"
    echo -n "   Deezer ARL cookie: "
    read -r deezer_arl
fi

echo -n "   Enable YouTube Music? (y/N): "
read -r youtube
youtube_enabled="false"
yt_client_id=""
yt_client_secret=""
if [ "$youtube" = "y" ] || [ "$youtube" = "Y" ]; then
    youtube_enabled="true"
    echo "   → Create credentials at https://console.cloud.google.com"
    echo "     Enable 'YouTube Data API v3', create OAuth 2.0 credentials"
    echo -n "   YouTube Client ID: "
    read -r yt_client_id
    echo -n "   YouTube Client Secret: "
    read -r yt_client_secret
fi

# --- Metadata enrichment ---
echo ""
echo -e "${CYAN}5. Metadata enrichment (optional, improves library quality)${NC}"

echo -n "   Discogs token (https://discogs.com/settings/developers) [skip]: "
read -r discogs_token

echo -n "   Last.fm API key (https://last.fm/api/account/create) [skip]: "
read -r lastfm_key

echo -n "   Radio France API key (https://developer.radiofrance.fr) [skip]: "
read -r radiofrance_key

# --- Write .env ---
echo ""
echo -e "${GREEN}Writing .env...${NC}"

cat > "$ENV_FILE" << ENVEOF
# Tune Server — Generated by setup.sh
TUNE_MUSIC_DIRS=["$music_dir"]
TUNE_SCAN_ON_STARTUP=true
TUNE_DB_ENGINE=$db_engine
ENVEOF

if [ "$db_engine" = "postgres" ]; then
    echo "TUNE_DB_URL=$db_url" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << ENVEOF
TUNE_API_PORT=$port

# Streaming
TUNE_TIDAL_ENABLED=$tidal_enabled
TUNE_QOBUZ_ENABLED=$qobuz_enabled
ENVEOF

if [ "$deezer_enabled" = "true" ]; then
    echo "TUNE_DEEZER_ENABLED=true" >> "$ENV_FILE"
    [ -n "$deezer_arl" ] && echo "TUNE_DEEZER_ARL=$deezer_arl" >> "$ENV_FILE"
    echo "TUNE_DEEZER_QUALITY=FLAC" >> "$ENV_FILE"
fi

if [ "$youtube_enabled" = "true" ]; then
    echo "TUNE_YOUTUBE_ENABLED=true" >> "$ENV_FILE"
    [ -n "$yt_client_id" ] && echo "TUNE_YOUTUBE_CLIENT_ID=$yt_client_id" >> "$ENV_FILE"
    [ -n "$yt_client_secret" ] && echo "TUNE_YOUTUBE_CLIENT_SECRET=$yt_client_secret" >> "$ENV_FILE"
fi

# Metadata
[ -n "$discogs_token" ] && echo "TUNE_DISCOGS_TOKEN=$discogs_token" >> "$ENV_FILE"
[ -n "$lastfm_key" ] && echo "TUNE_LASTFM_API_KEY=$lastfm_key" >> "$ENV_FILE"
[ -n "$radiofrance_key" ] && echo "TUNE_RADIOFRANCE_API_KEY=$radiofrance_key" >> "$ENV_FILE"

echo ""
echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""
echo -e "Start the server with:"
echo -e "  ${CYAN}tune-server${NC}"
echo -e "  or: ${CYAN}python -m tune_server${NC}"
echo ""
echo -e "Then open ${CYAN}http://localhost:$port${NC} in your browser."
echo ""
echo -e "For Tidal/Qobuz: go to Settings → Streaming to log in."
echo ""
